### ISSUE TITLE
setup.py for Birdman CLI

### ISSUE THREAD

**Issue by progmatic-99** [ILUGD/Birdman#12]
## Expected Behavior

To run the CLI we have to have click library pre-installed on the user's computer.
## Current Behavior

On the cmd line, user has to type "py main.py" to run the birdman CLI
## Possible Solution

setup.py file installs the click library and removes the need to include if __name__ == "__main__"
line or any she-bang.
After this fix, user has to type __birdman__ on the cmd line.

**Comment by pythongiant** [comment]
SGTM. Like to work on this?

**Comment by progmatic-99** [comment]
Working on it.
