### ISSUE TITLE
Create CLI client

### ISSUE THREAD

**Issue by pythongiant** [ILUGD/Birdman#2]
## Current Situation

We dont have a CLI client yet. we need it. You can use the [click](https://click.palletsprojects.com/en/7.x/) library for this. 

Have a look at the README 
1. https://github.com/ILUGD/Birdman#working
2. https://github.com/ILUGD/Birdman#extras

**Comment by ajax711** [comment]
Working on it

**Comment by nitishp25** [comment]
how does the frontend access the date time and venue of the meetup?

**Comment by pythongiant** [comment]
@nitishp25 meet up API

**Comment by progmatic-99** [comment]
I am working on the CLI.
